import re

company_regexes = {
    "3M": r"(?im)(\b3M\b)",
    "AB InBev (CCD)": r"(?im)(\bAB InBev|CCD\b)",
    "Abbott - OTC": r"(?im)(\bAbbott\b)",
    "Abbvie": r"(?im)(\bAbbvie\b)",
    "ABI": r"(?im)(\bABI\b)",
    "Adidas": r"(?im)(\bAdidas\b)",
    "Ahold Delhaize": r"(?im)(\bAhold Delhaize\b)",
    "AIG": r"(?im)(\bAIG\b)",
    "Airbnb": r"(?im)(\bAirbnb\b)",
    "Albertsons": r"(?im)(\bAlbertsons\b)",
    "Aldi": r"(?im)(\bAldi\b)",
    "AllBirds": r"(?im)(\bAllBirds\b)",
    "Allstate": r"(?im)(\bAllstate\b)",
    "Altria (BRS + Avail)": r"(?im)(\bAltria\b)",
    "Altria (Avail)": r"(?im)(\b((Altria)\W+(?:\w+\W+){0,9}?(Avail))|((Avail)\W+(?:\w+\W+){0,9}?(Altria))\b)",
    "Amazon": r"(?im)(\bAmazon\b)",
    "Amazon Whole Foods": r"(?im)(\bWhole Foods\b)",
    "AMERICA MOVIL": r"(?im)(\bAMERICA MOVIL\b)",
    "American Alliance of Museums": r"(?im)(\bAmerican Alliance of Museums\b)",
    "American Express": r"(?im)(\bAmerican Express\b)",
    "AmGen": r"(?im)(\bAmGen\b)",
    "Antenna Group": r"(?im)(\bAntenna Group\b)",
    "Anthem": r"(?im)(\bAnthem\b)",
    "Apple": r"(?im)(\bApple\b)",
    "Applied Research and Analysis Consulting": r"(?im)(\bApplied Research and Analysis Consulting\b)",
    "Appvion": r"(?im)(\bAppvion\b)",
    "Archer Daniels Midland": r"(?im)(\bArcher Daniels Midland\b)",
    "Aristocrat Gaming": r"(?im)(\bAristocrat Gaming\b)",
    "Arla Food": r"(?im)(\bArla Food\b)",
    "AstraZeneca": r"(?im)(\bAstraZeneca\b)",
    "ASURION LLC": r"(?im)(\bASURION LLC\b)",
    "AT&T": r"(?im)(\bAT\&T\b)",
    "Ateeco": r"(?im)(\bAteeco\b)",
    "Autodesk": r"(?im)(\bAutodesk\b)",
    "Bacardi": r"(?im)(\bBacardi\b)",
    "Bally Sports": r"(?im)(\bBally Sports\b)",
    "Bank of America": r"(?im)(\bBank of America\b)",
    "Bayer - OTC": r"(?im)(\bBayer\b)",
    "Becton, Dickinson & Co.": r"(?im)(\bBecton\, Dickinson \& Co\.\b)",
    "BYTEDANCE": r"(?im)(\bBYTEDANCE\b)",
    "CALERES": r"(?im)(\bCALERES\b)",
    "Campari USA": r"(?im)(\bCampari USA\b)",
    "CAMPBELL SOUP": r"(?im)(\bCAMPBELL SOUP\b)",
    "CAPITAL ONE FINANCIAL": r"(?im)(\bCAPITAL ONE FINANCIAL\b)",
    "Cardinal Health": r"(?im)(\bCardinal Health\b)",
    "Cargill": r"(?im)(\bCargill\b)",
    "Carnival Cruise Lines": r"(?im)(\bCarnival Cruise Lines|Carnival\b)",
    "CASEY'S": r"(?im)(\bCASEY\'S\b)",
    "Cash App": r"(?im)(\bCash App\b)",
    "Caterpillar": r"(?im)(\bCaterpillar\b)",
    "CDC": r"(?im)(\bCDC\b)",
    "Celerion": r"(?im)(\bCelerion\b)",
    "Celestial Hain": r"(?im)(\bCelestial Hain\b)",
    "Centene": r"(?im)(\bCentene\b)",
    "Centre for Substance Use Regulation": r"(?im)(\bCentre for Substance Use Regulation\b)",
    "Charles Schwab": r"(?im)(\bCharles Schwab\b)",
    "Cheerain HK Limited": r"(?im)(\bCheerain HK Limited\b)",
    "CHEVRON": r"(?im)(\bCHEVRON\b)",
    "Chow Now": r"(?im)(\bChow Now\b)",
    "CHS": r"(?im)(\bCHS\b)",
    "Church & Dwight": r"(?im)(\bChurch \& Dwight\b)",
    "CIRCLE K CONVENIENCE STORES": r"(?im)(\bCIRCLE K CONVENIENCE STORES|Circle K\b)",
    "Cisco": r"(?im)(\bCisco\b)",
    "CITIGROUP": r"(?im)(\bCITIGROUP\b)",
    "CITIZENS BANK": r"(?im)(\bCITIZENS BANK\b)",
    "CKE Restaurants": r"(?im)(\bCKE Restaurants\b)",
    "Clorox": r"(?im)(\bClorox\b)",
    "COCA-COLA": r"(?im)(\bCOCA\-COLA\b)",
    "Colgate": r"(?im)(\bColgate\b)",
    "COMCAST NBC UNIVERSAL - MEDIA": r"(?im)(\bCOMCAST NBC UNIVERSAL\b)",
    "Compassion International": r"(?im)(\bCompassion International\b)",
    "Con Edison": r"(?im)(\bCon Edison\b)",
    "ConAgra": r"(?im)(\bConAgra\b)",
    "Conair/Cuisinart": r"(?im)(\bConair/Cuisinart\b)",
    "ConocoPhillips": r"(?im)(\bConocoPhillips\b)",
    "CONSTELLATION BRANDS": r"(?im)(\bCONSTELLATION BRANDS\b)",
    "Consumer Cellular": r"(?im)(\bConsumer Cellular\b)",
    "Convoy": r"(?im)(\bConvoy\b)",
    "Costco": r"(?im)(\bCostco\b)",
    "Coterie": r"(?im)(\bCoterie\b)",
    "COTY": r"(?im)(\bCOTY\b)",
    "COUCHE TARD": r"(?im)(\bCOUCHE TARD\b)",
    "COX CABLE": r"(?im)(\bCOX CABLE\b)",
    "Cracker Barrel": r"(?im)(\bCracker Barrel\b)",
    "CVS": r"(?im)(\bCVS\b)",
    "Daimler AG": r"(?im)(\bDaimler AG\b)",
    "DANONE": r"(?im)(\bDANONE\b)",
    "DARDEN RESTAURANTS": r"(?im)(\bDARDEN RESTAURANTS\b)",
    "Deckers": r"(?im)(\bDeckers\b)",
    "Delaware North": r"(?im)(\bDelaware North\b)",
    "DELL": r"(?im)(\bDELL\b)",
    "Delta Airlines": r"(?im)(\bDelta Airlines\b)",
    "Demonstrate": r"(?im)(\bDemonstrate\b)",
    "DEPT. OF VETERANS AFFAIRS": r"(?im)(\bDEPT\. OF VETERANS AFFAIRS|Department of veteran\S* affairs|DEPT\ OF VETERANS AFFAIRS\b)",
    "Deutsch Telecom (TMO)": r"(?im)(\bDeutsch Telecom\b)",
    "DevaCurl": r"(?im)(\bDevaCurl\b)",
    "DIAGEO": r"(?im)(\bDIAGEO\b)",
    "DINE Brands/Applebee's": r"(?im)(\bDINE Brands|Applebee\'s\b)",
    "DOD": r"(?im)(\bDOD\b)",
    "DOD - FORSMARSH": r"(?im)(\b((DOD)\W+(?:\w+\W+){0,9}?(FORSMARSH))|((FORSMARSH)\W+(?:\w+\W+){0,9}?(DOD))\b)",
    "Domino's Pizza": r"(?im)(\bDomino\'s Pizza|Dominos\b)",
    "Doordash": r"(?im)(\bDoordash\b)",
    "DOT": r"(?im)(\bDOT\b)",
    "Dow Chemical Company": r"(?im)(\bDow Chemical Company|DOW\b)",
    "Dr Pepper Snapple": r"(?im)(\bDr Pepper|Snapple|Dr pepper snapple|dr\S* pepper snapple\b)",
    "Droga5": r"(?im)(\bDroga5\b)",
    "Duck Duck Go": r"(?im)(\bDuck Duck Go\b)",
    "E & J GALLO WINERY": r"(?im)(\bE \& J GALLO WINERY\b)",
    "e.l.f. Cosmetics": r"(?im)(\be\.l\.f\. Cosmetics\b)",
    "EDGEWELL": r"(?im)(\bEDGEWELL\b)",
    "Edward Jones": r"(?im)(\bEdward Jones\b)",
    "Ekaterra": r"(?im)(\bEkaterra\b)",
    "Elevance Health": r"(?im)(\bElevance Health\b)",
    "ELI LILLY": r"(?im)(\bELI LILLY\b)",
    "Energy Transfer Partners": r"(?im)(\bEnergy Transfer Partners\b)",
    "Enterprise Products": r"(?im)(\bEnterprise Products\b)",
    "ESTEE LAUDER COS": r"(?im)(\bESTEE LAUDER COS\b)",
    "Eventbrite": r"(?im)(\bEventbrite\b)",
    "EW Scripps": r"(?im)(\bEW Scripps\b)",
    "Exelon": r"(?im)(\bExelon\b)",
    "Expedia": r"(?im)(\bExpedia\b)",
    "ExxonMobil": r"(?im)(\bExxonMobil|Exxon\b)",
    "Farmer's Insurance": r"(?im)(\bFarmer\'s Insurance\b)",
    "Fastenal": r"(?im)(\bFastenal\b)",
    "FCA GROUP (FIAT/CHRYSLER GROUP)": r"(?im)(\bFCA GROUP|FIAT\/CHRYSLER GROUP\b)",
    "FEDERAL RESERVE": r"(?im)(\bFEDERAL RESERVE\b)",
    "FEDEX": r"(?im)(\bFEDEX\b)",
    "FERRERO": r"(?im)(\bFERRERO\b)",
    "First Horizon": r"(?im)(\bFirst Horizon\b)",
    "Fleetcor": r"(?im)(\bFleetcor\b)",
    "Flowers Foods": r"(?im)(\bFlowers Foods\b)",
    "Focus on the Family": r"(?im)(\bFocus on the Family\b)",
    "Ford Motor Company": r"(?im)(\bFord Motor Company|Ford\b)",
    "Foster Farms": r"(?im)(\bFoster Farms\b)",
    "Foundation CH": r"(?im)(\bFoundation CH\b)",
    "Fox Media": r"(?im)(\bFox Media|FOX\b)",
    "Frederick Wildman": r"(?im)(\bFrederick Wildman\b)",
    "Frontier Communications": r"(?im)(\bFrontier Communications\b)",
    "Gap": r"(?im)(\bGap\b)",
    "Gartner": r"(?im)(\bGartner\b)",
    "Geely Holding Group": r"(?im)(\bGeely Holding Group\b)",
    "General Dynamics": r"(?im)(\bGeneral Dynamics\b)",
    "GENERAL ELECTRIC + HAIER": r"(?im)(\bGENERAL ELECTRIC \+ HAIER|General electric|Haier|((General Electric)\W+(?:\w+\W+){0,9}?(Haier))|((Haier)\W+(?:\w+\W+){0,9}?(General Electric))\b)",
    "General Mills": r"(?im)(\bGeneral Mills\b)",
    "General Motors": r"(?im)(\bGeneral Motors\b)",
    "Givaudan": r"(?im)(\bGivaudan\b)",
    "Glassdoor": r"(?im)(\bGlassdoor\b)",
    "Goldman Sachs": r"(?im)(\bGoldman Sachs\b)",
    "GOOGLE": r"(?im)(\bGOOGLE\b)",
    "GOOGLE (Ad Sales)": r"(?im)(\bGOOGLE Ad Sales|((Google)\W+(?:\w+\W+){0,3}?(ad sales))|((ad sales)\W+(?:\w+\W+){0,9}?(google))\b)",
    "Gorton's Fish": r"(?im)(\bGorton\'s Fish\b)",
    "Goya": r"(?im)(\bGoya\b)",
    "GRUPO BIMBO": r"(?im)(\bGRUPO BIMBO\b)",
    "Gulf Oil": r"(?im)(\bGulf Oil\b)",
    "H & M": r"(?im)(\bH \& M\b)",
    "Haleon": r"(?im)(\bHaleon\b)",
    "Hamilton Beach": r"(?im)(\bHamilton Beach\b)",
    "Hanes Brands": r"(?im)(\bHanes Brands\b)",
    "Hard Rock": r"(?im)(\bHard Rock\b)",
    "Hartz": r"(?im)(\bHartz\b)",
    "HCA Healthcare": r"(?im)(\bHCA Healthcare\b)",
    "HEINEKEN HOLDING": r"(?im)(\bHEINEKEN HOLDING\b)",
    "Henkel": r"(?im)(\bHenkel\b)",
    "Hennessy": r"(?im)(\bHennessy\b)",
    "Hero Digital": r"(?im)(\bHero Digital\b)",
    "Hershey": r"(?im)(\bHershey\b)",
    "HEWLETT PACKARD": r"(?im)(\bHEWLETT PACKARD\b)",
    "HHS": r"(?im)(\bHHS\b)",
    "Hilton": r"(?im)(\bHilton\b)",
    "Hisense": r"(?im)(\bHisense\b)",
    "HOME DEPOT": r"(?im)(\bHOME DEPOT\b)",
    "Honda": r"(?im)(\bHonda\b)",
    "Honey Baked Ham": r"(?im)(\bHoney Baked Ham\b)",
    "Hormel": r"(?im)(\bHormel\b)",
    "Hostess Brands": r"(?im)(\bHostess Brands\b)",
    "HP Hood": r"(?im)(\bHP Hood\b)",
    "Hyatt": r"(?im)(\bHyatt\b)",
    "Hyundai/Kia": r"(?im)(\bHyundai\/Kia|hyundai|kia\b)",
    "IBM": r"(?im)(\bIBM\b)",
    "IKEA": r"(?im)(\bIKEA\b)",
    "ILLY CAFFE": r"(?im)(\bILLY CAFFE\b)",
    "Imperial Tobacco": r"(?im)(\bImperial Tobacco\b)",
    "Innventure": r"(?im)(\bInnventure\b)",
    "INSPIRE BRANDS INC": r"(?im)(\bINSPIRE BRANDS INC\S*\b)",
    "INSTACART": r"(?im)(\bINSTACART\b)",
    "Intel": r"(?im)(\bIntel\b)",
    "INTUIT": r"(?im)(\bINTUIT\b)",
    "J&J OTC": r"(?im)(\bJ\&J OTC\b)",
    "J.M. Smucker": r"(?im)(\bJ\.M\. Smucker\b)",
    "Jiffy": r"(?im)(\bJiffy\b)",
    "John Deere": r"(?im)(\bJohn Deere\b)",
    "JOHNSON & JOHNSON - PHARMA": r"(?im)(\bJOHNSON \& JOHNSON\b)",
    "JP MORGAN CHASE": r"(?im)(\bJP MORGAN CHASE\b)",
    "JUUL LABS": r"(?im)(\bJUUL LABS\b)",
    "KAISER PERMANENTE": r"(?im)(\bKAISER PERMANENTE\b)",
    "Kao Corporation": r"(?im)(\bKao Corporation\b)",
    "KELLOGGS": r"(?im)(\bKELLOGGS\b)",
    "Kimberly-Clark": r"(?im)(\bKimberly\-Clark\b)",
    "King's Hawaiaan": r"(?im)(\bKing\'s Hawaiaan\b)",
    "Kohl's": r"(?im)(\bKohl\'s\b)",
    "KRAFT HEINZ COMPANY": r"(?im)(\bKRAFT HEINZ COMPANY\b)",
    "KROGER": r"(?im)(\bKROGER\b)",
    "Kum & Go": r"(?im)(\bKum \& Go\b)",
    "LA Clippers": r"(?im)(\bLA Clippers\b)",
    "La Madeleine FrenchBakery & Café": r"(?im)(\bLa Madeleine FrenchBakery & Café|La Madeleine French Bakery and Cafe|La Madeleine French Bakery \& Cafe\b)",
    "LACTALIS": r"(?im)(\bLACTALIS\b)",
    "Lamb Weston": r"(?im)(\bLamb Weston\b)",
    "Lerma Agency": r"(?im)(\bLerma Agency\b)",
    "LEVI STRAUSS": r"(?im)(\bLEVI STRAUSS\b)",
    "LG INTERNATIONAL": r"(?im)(\bLG INTERNATIONAL\b)",
    "Liberty Mutual": r"(?im)(\bLiberty Mutual\b)",
    "Liberty Mutual Group": r"(?im)(\bLiberty Mutual Group\b)",
    "Life Time Fitness": r"(?im)(\bLife Time Fitness\b)",
    "Lincoln Financial": r"(?im)(\bLincoln Financial\b)",
    "LIV Golf": r"(?im)(\bLIV Golf\b)",
    "Lockheed Martin": r"(?im)(\bLockheed Martin\b)",
    "L'Oreal": r"(?im)(\bL\'Oreal\b)",
    "LOWES COS": r"(?im)(\bLOWES COS|Lowes\b)",
    "Luxottica Group": r"(?im)(\bLuxottica Group\b)",
    "LVMH \(splits with Ivana by house\)": r"(?im)(\bLVMH\b)",
    "Lyft": r"(?im)(\bLyft\b)",
    "MANSCAPED": r"(?im)(\bMANSCAPED\b)",
    "Manulife Financial": r"(?im)(\bManulife Financial\b)",
    "Marathon": r"(?im)(\bMarathon\b)",
    "Marriott": r"(?im)(\bMarriott\b)",
    "MARS \(MASTERFOOD\)": r"(?im)(\bMARS|Masterfood\b)",
    "Mastercard": r"(?im)(\bMastercard\b)",
    "Match.com": r"(?im)(\bMatch\.com\b)",
    "Mattel": r"(?im)(\bMattel\b)",
    "MAYO CLINIC": r"(?im)(\bMAYO CLINIC\b)",
    "Mazda": r"(?im)(\bMazda\b)",
    "McCain Food": r"(?im)(\bMcCain Food\b)",
    "McCormick & Co": r"(?im)(\bMcCormick \& Co\S*\b)",
    "MCDONALD'S": r"(?im)(\bMCDONALD\'S\b)",
    "McIntosh Group": r"(?im)(\bMcIntosh Group\b)",
    "McKesson Corporation": r"(?im)(\bMcKesson Corporation\b)",
    "MEDTRONIC": r"(?im)(\bMEDTRONIC\b)",
    "MERCK \(MSD\) - Pharma": r"(?im)(\bMERCK|MSD\b)",
    "Meta \(Facebook\)": r"(?im)(\bMeta\b)",
    "METLIFE": r"(?im)(\bMETLIFE\b)",
    "MGM": r"(?im)(\bMGM\b)",
    "MICROSOFT": r"(?im)(\bMICROSOFT\b)",
    "Mike's Hard Lemonda": r"(?im)(\bMike\'s Hard Lemonade\b)",
    "Milo's Tea": r"(?im)(\bMilo\'s Tea\b)",
    "Mitsubishi": r"(?im)(\bMitsubishi\b)",
    "MOEN INCORPORATED": r"(?im)(\bMOEN INCORPORATED\b)",
    "Moloco": r"(?im)(\bMoloco\b)",
    "Molson Coors": r"(?im)(\bMolson Coors\b)",
    "MONDELEZ": r"(?im)(\bMONDELEZ\b)",
    "Morton Salt": r"(?im)(\bMorton Salt\b)",
    "Mother LTD": r"(?im)(\bMother LTD\b)",
    "Motorola": r"(?im)(\bMotorola\b)",
    "My Bird Buddy": r"(?im)(\bMy Bird Buddy\b)",
    "My Fitness Pal": r"(?im)(\bMy Fitness Pal\b)",
    "NATIONAL AMUSEMENTS, INC.": r"(?im)(\bNATIONAL AMUSEMENTS\, INC\S*\b)",
    "Nationwide": r"(?im)(\bNationwide\b)",
    "Nature's Sunshine": r"(?im)(\bNature\'s Sunshine\b)",
    "Navy Federal": r"(?im)(\bNavy Federal\b)",
    "NBA": r"(?im)(\bNBA|National Basketball Association\b)",
    "Nestle": r"(?im)(\bNestle\b)",
    "Nestle Waters": r"(?im)(\bNestle Waters\b)",
    "NETFLIX": r"(?im)(\bNETFLIX\b)",
    "New York Life": r"(?im)(\bNew York Life\b)",
    "Newell Rubbermaid": r"(?im)(\bNewell Rubbermaid\b)",
    "Newman's Own": r"(?im)(\bNewman\'s Own\b)",
    "NEXTera/FPL": r"(?im)(\bNEXTera\/FPL|Nextera|fpl\b)",
    "NFL": r"(?im)(\bNFL|National Football Association\b)",
    "NIKE": r"(?im)(\bNIKE\b)",
    "Nissan Motor": r"(?im)(\bNissan Motor\b)",
    "NJOY": r"(?im)(\bNJOY\b)",
    "Nokia": r"(?im)(\bNokia\b)",
    "NOOM, INC.": r"(?im)(\bNOOM\, INC\S*\b)",
    "Norwegian Cruise Line": r"(?im)(\bNorwegian Cruise Line\b)",
    "NOVARTIS INTERNATIONAL": r"(?im)(\bNOVARTIS INTERNATIONAL\b)",
    "Nucor": r"(?im)(\bNucor\b)",
    "Ocean Spray": r"(?im)(\bOcean Spray\b)",
    "Olympics - LA28": r"(?im)(\bOlympics\b)",
    "Opryland": r"(?im)(\bOpryland\b)",
    "Oracle Corporation": r"(?im)(\bOracle Corporation\b)",
    "Oral Essentials": r"(?im)(\bOral Essentials\b)",
    "Pacific Life": r"(?im)(\bPacific Life\b)",
    "Panasonic": r"(?im)(\bPanasonic\b)",
    "Panda": r"(?im)(\bPanda\b)",
    "Paypal": r"(?im)(\bPaypal\b)",
    "PEPSICO": r"(?im)(\bPEPSICO\b)",
    "PERNOD RICARD": r"(?im)(\bPERNOD RICARD\b)",
    "PetCo": r"(?im)(\bPetCo\b)",
    "PETSMART": r"(?im)(\bPETSMART\b)",
    "PFIZER - PHARMA": r"(?im)(\bPFIZER\b)",
    "PHILLIPS 66": r"(?im)(\bPHILLIPS 66\b)",
    "Pilgrim’s": r"(?im)(\bPilgrim\’s\b)",
    "PITNEY BOWES": r"(?im)(\bPITNEY BOWES\b)",
    "Plains All American Pipeline": r"(?im)(\bPlains All American Pipeline\b)",
    "Planet Fitness": r"(?im)(\bPlanet Fitness\b)",
    "Planned Parenthood": r"(?im)(\bPlanned Parenthood\b)",
    "PMI US": r"(?im)(\bPMI US|PMI\b)",
    "PNC FINANCIAL SERVICES": r"(?im)(\bPNC FINANCIAL SERVICES\b)",
    "Post Foods": r"(?im)(\bPost Foods\b)",
    "Post Holdings": r"(?im)(\bPost Holdings\b)",
    "PPD": r"(?im)(\bPPD\b)",
    "Prestige Brands": r"(?im)(\bPrestige Brands\b)",
    "PROCTER & GAMBLE": r"(?im)(\bPROCTER \& GAMBLE\b)",
    "Progressive": r"(?im)(\bProgressive\b)",
    "ProTrans": r"(?im)(\bProTrans\b)",
    "Prudential": r"(?im)(\bPrudential\b)",
    "Publix": r"(?im)(\bPublix\b)",
    "Purchasing Power": r"(?im)(\bPurchasing Power\b)",
    "Qualcomm": r"(?im)(\bQualcomm\b)",
    "Raytheon Technologies": r"(?im)(\bRaytheon Technologies\b)",
    "RBI \(Restaurant Brands Intl\)": r"(?im)(\bRBI|Restaurant Brands Intl|Restaurant brands international\b)",
    "Reckitt - OTC": r"(?im)(\bReckitt\b)",
    "REDBULL": r"(?im)(\bREDBULL\b)",
    "Reddit": r"(?im)(\bReddit\b)",
    "RELX Technology": r"(?im)(\bRELX Technology\b)",
    "Remy Cointreau": r"(?im)(\bRemy Cointreau\b)",
    "RENAULT": r"(?im)(\bRENAULT\b)",
    "RingCentral": r"(?im)(\bRingCentral|ring central\b)",
    "Roku Inc": r"(?im)(\bRoku Inc\b)",
    "Royal Caribbean": r"(?im)(\bRoyal Caribbean\b)",
    "ROYAL DUTCH SHELL": r"(?im)(\bROYAL DUTCH SHELL\b)",
    "Royal Philips Electronics": r"(?im)(\bRoyal Philips Electronics\b)",
    "RSM": r"(?im)(\bRSM\b)",
    "Sabra": r"(?im)(\bSabra\b)",
    "SALESFORCE.COM": r"(?im)(\bSALESFORCE\.COM\b)",
    "Salt River Project": r"(?im)(\bSalt River Project\b)",
    "SAMSUNG": r"(?im)(\bSAMSUNG\b)",
    "San Francisco 49'ers": r"(?im)(\bSan Francisco 49\'ers\b)",
    "SANOFI - OTC": r"(?im)(\bSANOFI\b)",
    "SANOFI - PHARMA": r"(?im)(\bSANOFI|((sanofi)\W+(?:\w+\W+){0,3}?(pharma))|((pharma)\W+(?:\w+\W+){0,9}?(sanofi))\b)",
    "SANTANDER GROUP": r"(?im)(\bSANTANDER GROUP\b)",
    "Saputo": r"(?im)(\bSaputo\b)",
    "SC Johnson": r"(?im)(\bSC Johnson\b)",
    "Scooter's Coffee": r"(?im)(\bScooter\'s Coffee\b)",
    "Seven & I Holdings": r"(?im)(\bSeven \& I Holdings\b)",
    "Smartfrog Group": r"(?im)(\bSmartfrog Group\b)",
    "Snapchat": r"(?im)(\bSnapchat\b)",
    "SOCIAL SECURITY ADMINISTRATION": r"(?im)(\bSOCIAL SECURITY ADMINISTRATION\b)",
    "SONIC DRIVE-IN": r"(?im)(\bSONIC DRIVE\-IN|Sonic\b)",
    "Sony": r"(?im)(\bSony\b)",
    "Spotify": r"(?im)(\bSpotify\b)",
    "Square Enix": r"(?im)(\bSquare Enix\b)",
    "Staples": r"(?im)(\bStaples\b)",
    "STARBUCKS": r"(?im)(\bSTARBUCKS\b)",
    "State Farm": r"(?im)(\bState Farm\b)",
    "Stellantis": r"(?im)(\bStellantis\b)",
    "StoneX Group": r"(?im)(\bStoneX Group\b)",
    "Strategic Education": r"(?im)(\bStrategic Education\b)",
    "SUBARU": r"(?im)(\bSUBARU\b)",
    "SUNTORY HOLDINGS LIMITED": r"(?im)(\bSUNTORY HOLDINGS LIMITED\b)",
    "Synchrony": r"(?im)(\bSynchrony\b)",
    "Sysco": r"(?im)(\bSysco\b)",
    "TAKEDA - PHARMA": r"(?im)(\bTAKEDA\b)",
    "Tapestry": r"(?im)(\bTapestry\b)",
    "Target": r"(?im)(\bTarget\b)",
    "TATA GROUP": r"(?im)(\bTATA GROUP\b)",
    "TD Bank": r"(?im)(\bTD Bank\b)",
    "Televisa Univision": r"(?im)(\bTelevisa Univision\b)",
    "Tesla": r"(?im)(\bTesla\b)",
    "Thales Group": r"(?im)(\bThales Group\b)",
    "The Community": r"(?im)(\bThe Community\b)",
    "The Melting Pot": r"(?im)(\bThe Melting Pot\b)",
    "Thermo Fisher Scientific": r"(?im)(\bThermo Fisher Scientific\b)",
    "Tinder": r"(?im)(\bTinder\b)",
    "TJX": r"(?im)(\bTJX\b)",
    "Toyota Industries": r"(?im)(\bToyota Industries\b)",
    "TRAMONTINA USA": r"(?im)(\bTRAMONTINA USA\b)",
    "TRANE": r"(?im)(\bTRANE\b)",
    "Treehouse": r"(?im)(\bTreehouse\b)",
    "Trive Capital": r"(?im)(\bTrive Capital\b)",
    "TWITTER, INC.": r"(?im)(\bTWITTER\, INC\.)",
    "TYSON FOODS": r"(?im)(\bTYSON FOODS\b)",
    "U.S. POSTAL": r"(?im)(\bU\.S\. POSTAL|Postal Service\b)",
    "UBER TECHNOLOGIES": r"(?im)(\bUBER TECHNOLOGIES\b)",
    "Ulta Beauty": r"(?im)(\bUlta Beauty\b)",
    "UNDER ARMOUR, INC.": r"(?im)(\bUNDER ARMOUR\, INC\S*\b)",
    "UNILEVER": r"(?im)(\bUNILEVER\b)",
    "UNITEDHEALTH GROUP": r"(?im)(\bUNITEDHEALTH GROUP\b)",
    "UPS": r"(?im)(\bUPS\b)",
    "US BANK": r"(?im)(\bUS BANK\b)",
    "US Cellular": r"(?im)(\bUS Cellular\b)",
    "US GOVERNMENT": r"(?im)(\bUS GOVERNMENT\b)",
    "Workday": r"(?im)(\bWorkday\b)",
    "USAA": r"(?im)(\bUSAA\b)",
    "USHBC": r"(?im)(\bUSHBC\b)",
    "Valvoline": r"(?im)(\bValvoline\b)",
    "Vanguard": r"(?im)(\bVanguard\b)",
    "VERIZON COMMUNICATIONS": r"(?im)(\bVERIZON COMMUNICATIONS\b)",
    "VF CORP": r"(?im)(\bVF CORP\b)",
    "Vimergy": r"(?im)(\bVimergy\b)",
    "VISA": r"(?im)(\bVISA\b)",
    "Visit Orlando": r"(?im)(\bVisit Orlando\b)",
    "Vitamix": r"(?im)(\bVitamix\b)",
    "Volkswagen": r"(?im)(\bVolkswagen\b)",
    "WALGREENS": r"(?im)(\bWALGREENS\b)",
    "WAL-MART": r"(?im)(\bWAL\-MART|walmart|wal mart\b)",
    "WALT DISNEY": r"(?im)(\bWALT DISNEY|Disney\b)",
    "WARNER BROS. DISCOVERY": r"(?im)(\bWARNER BROS\. DISCOVERY|Warner Bros\b)",
    "Wayfair": r"(?im)(\bWayfair\b)",
    "Welch's": r"(?im)(\bWelch\'s\b)",
    "WELLS FARGO": r"(?im)(\bWELLS FARGO\b)",
    "WhatIF? Consulting": r"(?im)(\bWhatIF\? Consulting\b)",
    "Whirlpool": r"(?im)(\bWhirlpool\b)",
    "Who Gives A Crap": r"(?im)(\bWho Gives A Crap\b)",
    "Willo": r"(?im)(\bWillo\b)",
    "Wonderful": r"(?im)(\bWonderful\b)",
    "Words from the Woods / RTIC": r"(?im)(\bWords from the Woods|RTIC\b)",
    "WORLD BANK": r"(?im)(\bWORLD BANK\b)",
    "WWE": r"(?im)(\bWWE\b)",
    "Xmedia": r"(?im)(\bXmedia\b)",
    "Yasso": r"(?im)(\bYasso\b)",
    "YUM BRANDS": r"(?im)(\bYUM BRANDS\b)",
    "Zoom": r"(?im)(\bZoom\b)"}